Shopify/cli-ui

- lib/dev/ui/ansi.rb
- test/dev/ui/ansi_test.rb
👩‍💻 is turning out to be a fairly painful thing to try to print to a terminal.
> understand printing width of ZWJ sequences

- README.md
Before:
```
ruby my_app.rb
┏━━ ⭑ a ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃┏━━ 𝒾 b ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃┃┏━━ ? c ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃┃┃ ✗ wow
┃┃┃ ✗ such spin
┃┃┃ ✗ many glyph
┃┃┃┏━━ Task Failed: wow ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#<Class:0x007fba4912cba8>: #<Class:0x007fba4912cba8>
from /Users/mark.campbell/dev-ui/lib/dev/ui/stdout_router.rb:134:in `assert_enabled!'
from /Users/mark.campbell/dev-ui/lib/dev/ui/stdout_router.rb:96:in `run'
from /Users/mark.campbell/dev-ui/lib/dev/ui/spinner.rb:36:in `block in initialize'
┃┃┃┣━━ STDOUT …
```
> Add `enable` to README example so that example will work

- lib/dev/ui/spinner.rb
- lib/dev/ui/stdout_router.rb
- test/dev/ui/spinner_test.rb
> Allow SpinnerGroup tasks to update their title while running

- lib/dev/ui/spinner.rb
- test/dev/ui/spinner_test.rb
> Add non-block-from API for Spinner

- lib/dev/ui/interactive_prompt.rb
@T-TonyLiang @jules2689 here's what I mean
> Use a state machine for safer char parsing

- README.md
Documenting the changes added in: https://github.com/Shopify/cli-ui/pull/16
Related Issue: https://github.com/Shopify/cli-ui/issues/14
New README:
cc @jules2689 for review
> Documentation of Callbacks for Interactive Prompts

- lib/cli/ui/formatter.rb
- lib/cli/ui/frame.rb
- lib/cli/ui/stdout_router.rb
> Use +'' instead of String.new()

- lib/cli/ui/glyph.rb
- test/cli/ui/glyph_test.rb
Added a test and tested with a puts that it prints to my terminal (iTerm2 + tmux + zsh)
> Add the bug emoji as a glyph

- lib/cli/ui/progress.rb
- test/cli/ui/progress_test.rb
> Reduce jumpiness when rendering progress

- test/cli/ui/spinner_test.rb
> Fix output timing issue in CI

- test/test_helper.rb
> Fix deprecation of mocha/mini_test

- test/cli/ui/spinner_test.rb
Same as #55
As seen as https://github.com/Shopify/cli-ui/pull/84#issuecomment-533684534
> Fix timing issue in CI

- lib/cli/ui/prompt/options_handler.rb
- test/cli/ui/prompt_test.rb
Fixes #66.
Adds tests for values coming out of ask with multiple: true and fixes using OptionsHandler with multiple: true.
> Fix ask with options handler and multiple: true

- lib/cli/ui/frame.rb
- lib/cli/ui/spinner/spin_group.rb
- test/cli/ui/spinner_test.rb
> Add the elasped time with debriefing a SpinGroup failure

- .travis.yml
- Gemfile.lock
Also update to bundler 2 since that's the version installed on the CI container
> Bundle update

- lib/cli/ui/progress.rb
> Fix progress documentation about the percent and set_percent params

- lib/cli/ui/spinner/spin_group.rb
Though rare, I’ve run into a race condition a few times when updating the title of a spinner task. This happens when the spinner task thread calls `update_title` while the main thread is in the middle of `render`. If `update_title` finishes first then `@force_full_render` is set to true. Then when `render` finishes, it sets `@force_full_render` to false. So now the title wont get updated until the next full render. In my case, the spin task ends right away so we don’t do another full render and the title never gets updated. So a simple mutex fixes that
> Fix race condition when updating the title of a spinner task

- lib/cli/ui/color.rb
> Fix to americanized gray

- README.md
- lib/cli/ui/prompt.rb
- test/cli/ui/prompt_test.rb
> Add ability to set prompt instructions color

- lib/cli/ui/frame/frame_stack.rb
The frame stack used to be handled in environment variables, which served as a global variable that we could serialize relevant information we needed to track to. Now we want to support having frames handled across threads (e.g. in SpinGroups) and so we store that information in thread variables now.
> Move handling the frame stack to thread variables

- lib/cli/ui/ansi.rb
Introduced new methods into the ANSI class that enable activating and deactivating the alternate screen mode.
> Add methods for using alternate screen

- lib/cli/ui.rb
- lib/cli/ui/spinner.rb
forgot this in https://github.com/Shopify/cli-ui/pull/571
> Support printing to stderr in more spinner methods

- lib/cli/ui/prompt/interactive_options.rb
> Add behaviour for navigating keys
