lib/dev/ui/ansi.rb
lib/dev/ui/frame.rb
test/dev/ui/spinner_test.rb

Tmux doesn't print characters at the correct width. This got especially
noticable with our three-codepoint-with-joiner mascot emoji.
Frame borders are now rendered by:
1. Drawing a line across the screen
2. Rewinding to the start of line and writing the prefix
3. Seeking to near the end of the line and writing the suffix

Render frame borders without requiring correct emoji rendering

---

lib/dev/ui/spinner.rb
test/dev/ui/spinner_test.rb

At the moment, the only way a SpinGroup task can report failure is by
raising an excepting. Since SpinGroup generates a backtrace from the
exception, task failures are very noisy.
This PR allows tasks to return a special symbol `:task_failed` to indicate
to the SpinGroup that it failed. During debrief, SpinGroup doesn't generate
a backtrace for these kind of failure.

Allow SpinGroup tasks to report failure by returning special symbol

---

lib/dev/ui/progress.rb
test/dev/ui/progress_test.rb

@jules2689 @alanwushopify 
I think this will look better on some terminals -- also it prints a lot fewer formatting codes, which should speed up rendering a bit.

Render progress bar as spaces instead of blocks

---

lib/cli/ui/prompt.rb
lib/cli/ui/prompt/options_handler.rb
test/cli/ui/prompt/options_handler_test.rb
test/cli/ui/prompt_test.rb

Issue: https://github.com/Shopify/cli-ui/issues/14
- changing the API for handling interactive options, so that they are defined within a block of the `ask` method
- removed the `options` key in the `ask` API
- added a new class to represent the various options and their attached handling procedures
- changed documentation and modified tests
New usage:
```ruby
CLI::UI::Prompt.ask("What is your choice?") do |handler|
handler.add_option("Choice 1") { |c| puts "Choice 1" }
handler.add_option("Choice 2") { |c| puts "Choice 2" }
end
```
cc @jules2689 @burke for review

New API for Handling Interactive Options in Prompt

---

README.md

The call to `CLI::UI.ask` does not correctly display the prompt options as shown in the example. It'll display the question but not the options. This small correction to the readme shows the proper call that results in the options being shown .

Fix example prompt command

---

lib/cli/ui/prompt/interactive_options.rb
test/cli/ui/prompt_test.rb

Prior to this PR, if you were to create an option handler with a blank title (a title denoted by ""). CLI-UI would have issues when it came to scrolling. This is caused because when cli-kit updates the screen in response to user input (ex: scrolling), it needs to count how many lines to clear and update. When a blank option is given, this line is not accounted for and results in the error. The PR counts these blank lines that aren't accounted for and adds them back into the total line count.

Patch blank option name edge case

---

lib/cli/ui/stdout_router.rb
lib/cli/ui/version.rb

Ruby 2.5 changed `IO#write` from `write(string)` to `write(string, ...)`.  Before 2.5, `puts "Hello"` would call `write("Hello"); write("\n")`.  It now calls `write("Hello", "\n")`.

Fix StdoutRouter for ruby 2.5

---

lib/cli/ui/stdout_router.rb
test/cli/ui/stdout_router_test.rb
test/cli/ui/terminal_test.rb

This prepends a uuid to specific streams, allowing for easier debugging.
In our case, I'd like to make the duplicate output in CLI Kit's executor (https://github.com/Shopify/cli-kit/blob/master/lib/cli/kit/executor.rb#L11-L13) prepend with a UUID, meaning the log file will have prefixed entries split by command executed.

Add uuid option to help with debugging specific runs

---

lib/cli/ui/ansi.rb
lib/cli/ui/prompt/interactive_options.rb
lib/cli/ui/terminal.rb
test/cli/ui/prompt_test.rb

Implement a scrolling list.  `wait_for_actionable_user_input` stops re-rendering options when not necessary (midway through processing a ⬆️/⬇️ sequence) since it was causing some noticeable flicker, but also means that tests had to change more, since fewer lines are written.  `fmt_full_line` is needed now since the lengths of lines can change, which was not true before since the only thing that changed was the marker vs space and colour.  This also caused tests to change, prompting the `option_text` helper.
cc @Shopify/dev-infra 
Fixes #34

Fix interactive prompt for options > terminal rows

---

lib/cli/ui.rb
lib/cli/ui/spinner/spin_group.rb
lib/cli/ui/truncater.rb
test/cli/ui/truncater_test.rb

Add a truncater to prevent overlength output cascades in spingroup

---

lib/cli/ui/prompt.rb
lib/cli/ui/prompt/interactive_options.rb
test/cli/ui/prompt_test.rb

Returns an array of all selected options, potentially empty
Verified with scrolling, "Done" moves up.
---
Edit: Changed icons and style:

Add support for multiple selection in prompt

---

lib/cli/ui/ansi.rb
lib/cli/ui/progress.rb
lib/cli/ui/prompt.rb
lib/cli/ui/prompt/interactive_options.rb
test/cli/ui/progress_test.rb
test/cli/ui/prompt_test.rb

`CLI::UI::ANSI.end_of_line` was broken in a couple of ways.  First, it didn't actually move to the end of the line, it advanced the cursor by one place.  Second, it was printing an extra escape sequence opener to do so (`\e[\e[C` instead of `\e[C`).  Some terminals were ignoring this invalid output, but others showed a character for it.
Given it wasn't doing the job it advertised, and that I could not find a trivial sequence that would, and where it was being used it clearly wasn't needed since it wasn't doing the job we thought it was, I removed it, and adjusted the places where it was being used.
Fixes #39.

Fix ansi problem

---

lib/cli/ui.rb
lib/cli/ui/prompt.rb
test/cli/ui/prompt_test.rb

This is something of a convenience that I've started emulating for "dangerous" options in a couple of tools I help maintain.
Figured it might be useful to other people.

Add flag to `confirm` that puts "no" first

---

lib/cli/ui/formatter.rb
lib/cli/ui/prompt.rb
test/cli/ui/formatter_test.rb

Not sure if this is the best way to go about this.  It works, but just counting braces seems a bit... brute force, I suppose.
Fixes #37

Prevent mismatched braces in format string

---

lib/cli/ui/prompt/interactive_options.rb

I ran into this issue while trying to diagnose an unrelated issue a coworker was having.  Currently, when lines longer than the width of the terminal are displayed, the wrapping causes the re-render to paint over an incorrect number of lines.  This results in something like this:
For this particular display, options numbered less than 24 aren't ever visible.
With these changes, all options are correctly displayed:

Take line wrapping into consideration when counting lines

---

cli-ui.gemspec
lib/cli/ui/formatter.rb
test/cli/ui/formatter_test.rb

When we updated this in `dev`, we found a legitimate use-case for mismatched braces, which had a useful behaviour:
We, in some cases, split a message with format codes on newline and emit each line independently. Format codes are allowed to span multiple lines and seem to work as you might expect, and brace counting causes :boom: in these cases.
IMO I'm not totally against revising our code to do better at this but I don't really feel like this runtime check provides enough value to carry its weight.

No brace counting

---

README.md
lib/cli/ui/prompt.rb
lib/cli/ui/prompt/interactive_options.rb
test/cli/ui/prompt_test.rb

Provides a couple of methods for searching/selecting in long lists of items.  Currently, I've added two methods: line selection and filtering.
Line selection works by eating numeric inputs to "build" the line you're trying to select.  So, entering '1'  -> '0' will select option 10.
Filtering works by comparing a built string to the full text of the option, hiding those that don't match.  Since options may no longer appear, I've modified the "selection" logic to be based on the filtered options.  This also means that figuring out how "far" from the top or bottom of the list is now determined by the index of the selected option rather than the number of the selected object.
I've also had to add logic to make sure the active selection is visible and resetting it if it's not.
Since the …

Interactive search options for long lists of options

---

lib/cli/ui/prompt.rb
test/cli/ui/prompt_test.rb

This PR allows prompting for options with only single elements, allowing for cases where nothing is selected. 
Fixes Shopify/subscribe#8
(I ran into this issue earlier today and impatiently opened Shopify/subscribe#9 to address it, but automatically choosing single options is the wrong thing to do.)
@lavoiesl

Allow single options

---

lib/cli/ui/prompt/interactive_options.rb

Implemented simple fix by just having the left and right key inputs ignored so they don't drop into the `else` clause where an exception is raised.

Fixes #63 by ignoring left and right keypresses

---

lib/cli/ui/prompt.rb
lib/cli/ui/version.rb

`STDIN.noecho` interacts poorly with Readline under system Ruby, so this code:
```rb
STDIN.noecho do
CLI::UI.ask()
end
```
Could end up printing the password to the terminal.
No fancy Readline integration (like echoing back) is required for a password prompt, so we can simply use a regular `STDIN.gets`.

Add an ask_password prompt

---

lib/cli/ui/frame.rb

Let's finally fix the crap frame formatting in buildkite

Don't use cursor save/restore in CI

---

lib/cli/ui.rb
lib/cli/ui/printer.rb
test/cli/ui/printer_test.rb

- Print a message to a stream with common utilities.
- Allows overriding the color, encoding, and target stream.
- By default, it formats the string using CLI:UI and rescues common stream errors.
Inspired by https://github.com/Shopify/cli-kit/pull/50

Add a puts method

---

lib/cli/ui/prompt/interactive_options.rb

Only include printing characters.
I came across this because a user was seeing odd output behaviour with `dev init`.  In debugging, I saw that she was using Terminal.app and thought it was the culprit.  But it went away when I maximized. Turns out the problem was the default width of Terminal.app of 80 - it misbehaved with a width of 80 or fewer columns. 80 being 80, I chased the wrong things for a while, but it turns out that 80 is the cut off where an option of ` 'Scaffold an entirely new {{bold:project}} with a {{bold:{{green:dev.yml}}}}'` seemed to overflow to a new line if you count all the characters in that string (75) instead of the characters in `'Scaffold an entirely new project with a dev.yml'` (47).

Fix interactive option line length calculation

---

.gitignore
.rubocop.yml
.travis.yml
Gemfile.lock
Rakefile
cli-ui.gemspec
lib/cli/ui.rb
lib/cli/ui/color.rb
lib/cli/ui/formatter.rb
lib/cli/ui/frame.rb
lib/cli/ui/progress.rb
lib/cli/ui/prompt.rb
lib/cli/ui/prompt/interactive_options.rb
lib/cli/ui/spinner/spin_group.rb
lib/cli/ui/stdout_router.rb
lib/cli/ui/terminal.rb
lib/cli/ui/truncater.rb
test/cli/ui/color_test.rb
test/cli/ui/glyph_test.rb
test/cli/ui/printer_test.rb
test/cli/ui/prompt/options_handler_test.rb
test/cli/ui/prompt_test.rb
test/cli/ui/spinner_test.rb
test/cli/ui/stdout_router_test.rb
test/cli/ui/terminal_test.rb
test/cli/ui/truncater_test.rb

The linter hasn't been run for a while, the CI wasn't enforcing it.
- Import rubocop configs from cli-kit (sister project)
- Commit Gemfile.lock, like on cli-kit
- Change target version of rubocop to 2.3
- Change bundler version in travis config to match the gemfile.lock
It's worth noting that the 2.1 parser isn't supported after rubocop
0.58 _and_ that it wasn't even passing because this project uses `<<~`, which isn't valid 2.1
syntax. `dev.yml` is also configured to use ruby 2.3

Update rubocop and fix linting

---

.travis.yml
lib/cli/ui/stdout_router.rb

Ruby version 2.3 is no longer officially supported so I think it's probably a good idea to bump the version tested to 2.4 - which is still supported.
Additionally, newer versions of bundler support automatic use of older versions when detected in the Gemfile.lock.  So, it should be safe to install the latest version of bundler even if the lockfile specifies an older version.

Update CI dependencies

---

lib/cli/ui/terminal.rb

This was brought to my attention by a co-worker.  Well behaved terminals issue a SIGWINCH when the window size changes, so it should be safe to cache width and height values until such a signal is received.
I figured it was safer to simply clear the cache when such a signal is received in case multiple are received in a very short period of time.  My terminal only issues a winch when the terminal has finished resizing, but I didn't think it wise to expect that to be standard behavior.
While I was at it, I wasn't sure if there was a particular reason to look up IO.console each time; It seems like one of those things that will either work or not.  If there was a reason it needed to be looked up constantly, I can pop those commits off.

Cache More Aggressively in CLI::UI::Terminal

---

lib/cli/ui/stdout_router.rb

Here's the doc:
Writes the given strings to ios. The stream must be opened for
writing.  Arguments that are not a string will be converted to a
string using to_s. Returns the number of bytes written in total.
So we're currently only passing the first arg, if multiple, to the hook.
I refactored while I'm at it here, the only actual change is replacing `hook.call(args.first, ...` with `hook.call(args.map(&:to_s).join, ...`

IO#write(string, ...), not IO#write(string):

---

README.md

Quick fix to change the order of the symbols in README to match the image below

Fixed order of symbols in readme

---

lib/cli/ui/prompt/interactive_options.rb

Closes https://github.com/Shopify/production-excellence/issues/57
Part of the `dev runtime` UI relies on multi-select menus. Our experience so far with the multi-select menu in cli-ui has prompted us to propose a change:
- Make the `Done` option selectable via cursor
- Move the `Done` option to the bottom (but keep its option number as `0`)
Before this change:
After this change:
- Currently, we don't pin the `0. Done` option so that it's always visible (in the case of a very long list of options that extend past the screen). Since this seems unlikely, and wasn't implemented for when `Done` is at the top, I haven't done so, here.
- There's no helpful prompt (e.g. `press '0' when Done`). One could argue that the fact that `0. Done` has no checkmark should be a good enough indicator of what …

multi-select DONE is selectable and at end of menu

---

dev.yml

I needed to poke around in this gem and had `openssl` problems when doing `dev up`. Ruby 2.3.3 is pretty old. Originally, I used 2.7.0, like in `cli-kit`, but that caused test failures. So... I used the latest version in `.travis.yml` (2.5.1).

Upgrades to ruby@2.5.1

---

lib/cli/ui/prompt/interactive_options.rb

Ruby 2.7 changed case equality for string ranges. We're comparing to a character here, so we should have maxed out at 9 anyway.
```
$ /opt/rubies/2.6.5/bin/ruby -e 'puts ("0".."10") === "2"'
true
$ /opt/rubies/2.7.1/bin/ruby -e 'puts ("0".."10") === "2"'
false
```

Fix a bug under ruby 2.7

---

lib/cli/ui/prompt.rb
lib/cli/ui/prompt/interactive_options.rb
test/cli/ui/prompt_test.rb

We want to be able to provide pre-selected values when asking with `multiple: true`. I went with a new argument because of this:
https://github.com/Shopify/cli-ui/blob/61c55842c54cda43dc7522881c26dc606c5fdfcb/lib/cli/ui/prompt.rb#L91-L93
Would it be better to use `:default` and avoid raising on that line if `:multiple == true`? What's the rationale behind that check?

Allow setting defaults for `CLI::UI::Prompt.ask(multiple: true)`

---

lib/cli/ui/prompt/interactive_options.rb

Drastically reduces the number of iterations needed to determine displayed options by trimming the list down to, at most, `max_length * 2` items.
On my machine, this speeds up list rendering to the point that the render loop spends most of its time waiting for user input.

Improve Performance of Interactive Options Over Large Lists

---

lib/cli/ui.rb

Warning was:
```
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

Fix deprectaion warning: kwargs

---

lib/cli/ui/frame.rb
lib/cli/ui/frame/frame_style/box.rb
lib/cli/ui/frame/frame_style/bracket.rb

While I was fixing the issue from #143, I noticed that bracket style printing had also been broken by the switch back to having Frame print the final space.  This PR fixes both.
Fixing the bracket frame style required printing it similarly to the box style (using `print_at_x`) instead of the more naive way I'd originally written.
I've been trying to figure out if there are any tests that we could potentially add to surface these kinds of issues, but, based on some comments about the CI server and the lack of existing Frame tests, I assume that such a thing is difficult to impossible to automatically test.  Perhaps a simple printout of some common frame situations and a progress bar (both in and out of a frame) as a sort of visual check that can be performed when running tests?

Fix prefix_width not accounting for final space; Fix frame_style/bracket

---

lib/cli/ui.rb
lib/cli/ui/ansi.rb
lib/cli/ui/frame/frame_style/box.rb
lib/cli/ui/glyph.rb
lib/cli/ui/os.rb
lib/cli/ui/prompt.rb
lib/cli/ui/prompt/interactive_options.rb
lib/cli/ui/spinner.rb
test/cli/ui/ansi_test.rb
test/cli/ui/glyph_test.rb
test/cli/ui/prompt_test.rb
test/cli/ui/spinner_test.rb
test/test_helper.rb

We are adapting the Shopify CLI (https://github.com/Shopify/shopify-app-cli) to work natively on Windows. While making those changes, we noted a few issues on the CLI UI specifically on Windows. This PR attempts to fix those issues.
Here is a list of the changes that were made:
* The UI Prompt can't handle the up / down arrow keys because Windows doesn't capture those keystrokes natively. After a bit of searching, it seems that it may be possible to make it work by using external gems (such as the deprecated Win32API or Fiddle), which are not an option here.
* The proposed fix is to simply not indicate that as an option as pressing those keys does nothing.
* Windows terminals don't seem to deal properly with emojis just yet (there is an open issue on their Github repo), so this PR changes …

Fix UI issues on Windows

---

lib/cli/ui.rb
lib/cli/ui/ansi.rb
lib/cli/ui/frame/frame_style/box.rb
lib/cli/ui/glyph.rb
lib/cli/ui/os.rb
lib/cli/ui/prompt.rb
lib/cli/ui/prompt/interactive_options.rb
lib/cli/ui/spinner.rb
test/cli/ui/ansi_test.rb
test/cli/ui/glyph_test.rb
test/cli/ui/printer_test.rb
test/cli/ui/prompt_test.rb
test/cli/ui/spinner_test.rb
test/test_helper.rb

This PR fixes the issues that occur when a box is printed with too long preambles or suffixes so that they overlap with the next elements in the line. The changes to support the UI on Windows failed on negative indexes that happened because of those extra-long lines.
I've reverted the box code to what it was before, and instead simply shift the cursor back on Windows.
After these changes:
```
irb(main):002:0> CLI::UI::Frame.open(('aa'..'zz').to_a.join)
┏━━ aaabacadaeafagahaiajakalamanaoapaqarasatauavawaxayazbabbbcbdbebfbgbhbibjbkblbmbnbobpbqbrbsbtbubvbwbxbybzcacbcccdcecfcgchcicjckclcmcncocpcqcrcsctcucvcwcxcyczdadbdcdddedfdgdhdidjdkdldmdndodpdqdrdsdtdudvdwdxdydzeaebecedeeefegeheiejekelemeneoepeqereseteuevewexeyezfafbfcfdfefffgfhfifjfkflfmfnfofpfqfrfsftfufvfwfxfyfzgagbgcgdgegfggghgigjgkglgmg …
```

Revert "Revert "Fix UI issues on Windows""

---

lib/cli/ui.rb
lib/cli/ui/frame/frame_stack.rb
lib/cli/ui/frame/frame_style.rb

Motivated by the desire to have `StackItem`s raise at initialization when they're invalid to make it easier to track down a bug where that's happening.

Clean up StackItems

---

lib/cli/ui/printer.rb

`:stream` and `:color` parameters no longer exist, so I rewrited example to match current version.

Update example of Printer.puts

---

lib/cli/ui/prompt/interactive_options.rb

Only works for Ruby 2.7 and up
Windows users would face a queued up "return" character when navigating after filtering options. @paulomarg and I found that instead of using `$stdin.getc`, `$stdin.getch` resolves this issue.

Resolve windows navigation error

---

cli-ui.gemspec

I tried packaging the gem for openSUSE to have it as a dependency for a project of mine, which worked.
The [build log](https://build.opensuse.org/package/live_build_log/home:expeehaa/rubygem-cli-ui/openSUSE_Tumbleweed/x86_64) shows some warnings though:
```
[   18s] ruby2.7-rubygem-cli-ui.x86_64: W: hidden-file-or-dir /usr/lib64/ruby/gems/2.7.0/gems/cli-ui-1.5.0/.dependabot
[   18s] ruby2.7-rubygem-cli-ui.x86_64: W: hidden-file-or-dir /usr/lib64/ruby/gems/2.7.0/gems/cli-ui-1.5.0/.dependabot
[   18s] ruby2.7-rubygem-cli-ui.x86_64: W: hidden-file-or-dir /usr/lib64/ruby/gems/2.7.0/gems/cli-ui-1.5.0/.github
[   18s] ruby2.7-rubygem-cli-ui.x86_64: W: hidden-file-or-dir /usr/lib64/ruby/gems/2.7.0/gems/cli-ui-1.5.0/.github
[   18s] ruby2.7-rubygem-cli-ui.x86_64: W: hidden-file-or-dir …
```

Include only important files in a gem build.

---

.travis.yml
test/cli/ui/progress_test.rb

It seems like the library itself works out-of-the-box with ruby 3.0.0. Only one test had to be adjusted.

Add compatibility for Ruby 3.0.0.

---

lib/cli/ui/frame/frame_style/bracket.rb

This mirrors the behaviour in the box frame style.

Restore cursor after rendering bracket frame edge

---

lib/cli/ui/formatter.rb

Gray and White area listed in color.rb but aren't available as e.g. `{{gray:words}}`

Add a couple of colours listed in Color to the Formatter

---

lib/cli/ui/prompt.rb
lib/cli/ui/prompt/interactive_options.rb

It's surprising, and not necessary. Anyone wishing to change the frame color can now put their prompt inside a
```ruby
CLI::UI.with_frame_color(:blue) do
...
end
```
to take control, which wasn't previously an option. The previous behaviour wasn't even a reliable change, since the prompts can occur outside of frames.
Fixes #271.

Stop changing the frame color for any prompt

---

lib/cli/ui.rb

They're supported by iTerm and Kitty, and falls back nicely to the text portion on terminal emulators that don't support them.
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

Support terminal links

---

lib/cli/ui/prompt/interactive_options.rb

Seems `:timeout` is no longer used, so we remove it at the same time.

Handle end of input in InteractiveOptions

---

lib/cli/ui/prompt/interactive_options.rb

While working [on introducing `ink`](https://github.com/Shopify/cli/pull/512) in CLI3 we (me and @Arkham) noticed that using `Ctrl+C` was raising the `Errno::EIO` exception inside `read_char`. We think introducing `ink` perhaps messed up with the order of operations when exiting all the processes and left the CLI2 process in a bad state where it would read from a closed pipe.
This PR introduces 2 more errors to rescue from. When these errors occur we should ignore them and simply terminate without raising exception.
You can [pull the cli `ink` work branch](https://github.com/Shopify/cli/pull/512) and run `dev fixture dev`. Closing with `Ctrl+C` after the theme-extension output should show a stracktrace with the `Errno::EIO` error.
We tested this fix by editing manually the vendored …

Rescue Errno::EIO in read_char

---

lib/cli/ui.rb

This exposes a convenience method for `CLI::UI::Prompt.any_key` (added in #375), to match the other convenience methods.
No convenience method is added for `CLI::UI::Prompt.read_char`, as it seems low level enough not to warrant it.

Expose `CLI::UI.any_key` convenience method

---

lib/cli/ui/ansi.rb
lib/cli/ui/prompt.rb
lib/cli/ui/spinner/spin_group.rb
lib/cli/ui/stdout_router.rb
vendor/reentrant_mutex.rb

SpinGroup runs Tasks inside of threads, which previously presented difficulties for handling sources of input. In this change, we have added support for a Mutex that supports reentrance as well as handling global variables in thread variables. This way we can communicate a thread's intent to read input, block other threads from doing so until the input is collected, and move on safely.
Fixes #281

Add support for interactive prompts in SpinGroup

---

lib/cli/ui/prompt.rb

I wanted to write a test for a script that uses this gem that simulates user input by overriding stdin and captures stdout/stderr output in a string to be printed only if the test fails to avoid cluttering the test output.
I did this with a `StringIO` object as such in my test:
```
test 'something' do
stdout = StringIO.new
$stdout = stdout
[call function which calls `CLI::UI.ask`]
$stdout = STDOUT
end
```
The problem is that this works for some of Cli-ui's output like frames, but not the prompts. It seems that this is because the prompts always write to `STDOUT` whereas other outputs write to `$stdout`. The difference between these in Ruby being that `$stdout` can be changed whereas `STDOUT` is a constant. This SO answer explains it in more depth: …

Be consistent with $stdout vs STDOUT

---

lib/cli/ui/stdout_router.rb
vendor/reentrant_mutex.rb

Given that `ReentrantMutex` was defined at the top level, it conflicts with other definitions of the same name like the one the [logging](https://github.com/TwP/logging/blob/b77368369ae7f323c65eebcd8d8c3aca64188925/lib/logging/utils.rb#L146-L169) gem defines.
So, if `cli-ui` is loaded after `logging`, it breaks the `logging` gem (and vice-versa)

📦️ Define ReentrantMutex inside CLI::UI module to avoid conflicts

---

lib/cli/ui/frame.rb
lib/cli/ui/frame/frame_style/box.rb
lib/cli/ui/frame/frame_style/bracket.rb
test/cli/ui/printer_test.rb

journald doesn't handle carriage returns well so we handle it similar to $CI and avoid outputting them when $JOURNAL_STREAM is set. journald also gets tripped up by the broken color codes we were accidentally outputting sometimes when chopping the last character of a frame's prefix so that's been addressed too.
This doesn't fix things like spinners but is still a nice improvement over the current output.
---
running one of the examples in the README.md via `systemd-run -d bundle exec ruby example.rb`:
before:
```
Jul 08 00:10:30 systemd[1]: Started /home/spin/.bundle/cli-ui/bin/bundle exec ruby example.rb.
Jul 08 00:10:34 bundle[37770]: [282B blob data]
Jul 08 00:10:34 bundle[37770]: [287B blob data]
Jul 08 00:10:34 bundle[37770]: [284B blob data]
Jul 08 00:10:34 bundle[37770]: [20B blob …
```

Fix frames in journald

---

lib/cli/ui.rb
lib/cli/ui/frame.rb
lib/cli/ui/frame/frame_style/box.rb
lib/cli/ui/frame/frame_style/bracket.rb
lib/cli/ui/spinner.rb
lib/cli/ui/spinner/spin_group.rb
test/test_helper.rb

This applies `CLI::UI.enable_color?` to Frame and Spinner output, and adds `CLI::UI.enable_cursor?` to disable cursor control when it's not supported.
I considered adding these as a parameters to Frame and Spinner, but it ended up bloating the code for little tangible benefit as these settings are usually static for the lifetime of the program. If we wanted to support something like that, I think the best approach would be to bundle color + cursor control settings along with `IOLike` as a sort of printing context. Nothing here prevents us from doing that in the future if the need arises.
---
for comparison here's the output of one of the examples from the README piped into `less`
before:
after:

Improve log output

---

.github/workflows/ruby.yml

`rubocop-sorbet` now requires ruby 3+

Drop ruby 2.7 from CI

---

lib/cli/ui/ansi.rb
test/cli/ui/ansi_test.rb

This makes it possible to compute the width of text that contains hyperlinks. We currently only strip OSC sequences that end in ST. Sometimes OSC sequences can end in BEL, but this is apparently non-standard. We can support it in the future if the need arises.

Strip OSC sequences

---

lib/cli/ui/wrap.rb
test/cli/ui/wrap_test.rb

We need to be able to apply .wrap to arbitrary widths in subshells where the terminal width isn't necessarily the final width of the display area.

Introduces a width parameter to CLI::UI::Wrap

---

lib/cli/ui/prompt.rb
lib/cli/ui/prompt/interactive_options.rb
test/cli/ui/prompt_test.rb

I've got a long list I want someone to choose one item from, but there's already a selected element. That element might be number 50 in a list (and often what the user wants is a nearby option). So instead of starting at the top every time and scrolling, allow default to be used to set the `active` element in a prompt and if a user just presses enter, they keep the element that was previously selected.

Allow default without multiple choices

---

lib/cli/ui/prompt.rb
test/cli/ui/prompt_test.rb

Fixes #500.
Regression was introduced in #380 (cc @arcadia-rose @lugray).
It was hanging, because it was in the infinite loop https://github.com/Shopify/cli-ui/blob/11302d0108e9e08df47c9e29e10e9896cfa52833/lib/cli/ui/spinner/spin_group.rb#L307-L313

Fix running spinners inside prompt callbacks

---

lib/cli/ui/spinner/spin_group.rb
test/cli/ui/spinner/spin_group_test.rb

This change adds new capabilities to `SpinGroup`:
- `interrupt_debrief`: This option, specified when initializing the `SpinGroup`, displays the debrief when the `SpinGroup` is interrupted. This is useful to interrupt and see an error without waiting for all tasks to complete.
- `SpinGroup#stop`, `SpinGroup#stopped?`: Programmatic support for stopping a `SpinGroup`. Exposing this method allows a `SpinGroup` to be stopped when a task fails, which can be used to implement fail-fast behavior.
- `SpinGroup::Task#on_done`: Support for a callback executed when a task transitions to done. This can be used to take action based on success or failure, and again can be used as part of an implementation of fail-fast behavior.
The "primitives" above are implemented instead of a specific "fail-fast" …

Add support to stop SpinGroup and show interrupt debrief

---

lib/cli/ui/ansi.rb
lib/cli/ui/spinner/spin_group.rb

This is useful for things like printing out a stream of logs while you have one or more spinners reporting on the current status. We could also add Spinner.puts_above, but when you have multiple Spinners, "above" is kind of ambiguous. We can add it later if the need becomes obvious.

Add SpinGroup.puts_above

---

lib/cli/ui/prompt/interactive_options.rb
test/cli/ui/prompt_test.rb

I have a user that brought up a concern around the automatic selection of an option when `1` is selected but there are 10+ options. The user expected to enter a select mode so they could enter 10, but it automatically selected option 1. Unfortunately this started a deletion of their branch (as the select prompt was to select a branch to delete), which the user was surprised by.
https://github.com/user-attachments/assets/0ca2f2c9-2ce2-40c0-b13e-f391a59aa99f
This PR is proposing to enter the _select mode_ when the user selects `1` and there are 10+ options (2 when there are 20+, etc).
https://github.com/user-attachments/assets/4df6d2ca-56fc-4164-9ec4-eb1a3bf13ac4
This is anticipated to make the select option a little bit safer, though does introduce some (albeit minor) inconsistency by not …

Add support to enter select mode when user has 10+ opts

---

Gemfile.lock
lib/cli/ui/color.rb
lib/cli/ui/formatter.rb
test/cli/ui/color_test.rb
test/cli/ui/formatter_test.rb
test/cli/ui/glyph_test.rb

Fixes https://github.com/Shopify/deploys/issues/1478
- c476c9bf93cc12a706973c64a5570b1bc2a7ef04: Fix the bug, with hard-coded tests
- 25d1ee48718a86353cb3ff18f4bdadf7ab91d4d6: Improve tests to be more dynamic and mitigate a bug like this in the future
This was [discovered in conveyor](https://github.com/shop/world/blob/64f6378f32173019826fb1ee85dab32024a6471c/areas/tools/dev/lib/conveyor/commands/deploy_release.rb#L23) when attempting to print the hourglass glyph with `{{H}}` and the `orange` color was not available to the formatter.
```
/opt/dev-dist/revisions/6814a86/vendor/deps/cli-ui/lib/cli/ui/formatter.rb:136:in `rescue in block in apply_format': invalid format specifier: orange (CLI::ui::Formatter::FormatError)
from /opt/dev-dist/revisions/6814a86/vendor/deps/cli-ui/lib/cli/ui/forma …
```

fix missing color from list of available colors

---

lib/cli/ui.rb

This is causing me problems with MacVim but it's a general rule that if `TERM=dumb`, color escape codes and cursor handling are not supported, so we shouldn't be emitting them.

Don't enable color or cursor with TERM=dumb
